services:
  llm-proxy:
    image: ghcr.io/lukacek/simple-aiproxy:latest
    container_name: llm-proxy
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config.yml:/app/config.yml:rw
      - ./app.db:/app/app.db:rw
    mem_limit: 512m
    networks:
      - proxy

networks:
  proxy:
    external: true
